<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459525502049" level="ERROR" thread="11"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable>System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
   à System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   à System.Data.Entity.Internal.InternalContext.Initialize()
   à System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   à System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   à System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   à System.Data.Entity.Internal.Linq.InternalSet`1.get_Local()
   à System.Data.Entity.DbSet`1.get_Local()
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 170</log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="205" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459525621682" level="ERROR" thread="6"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable>System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
   à System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   à System.Data.Entity.Internal.InternalContext.Initialize()
   à System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   à System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   à System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   à System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.IEnumerable.GetEnumerator()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 44
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 168</log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="207" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459525623678" level="ERROR" thread="14"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable><![CDATA[System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: There is already an open DataReader associated with this Connection which must be closed first.
   à MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\Interceptors\ExceptionInterceptor.cs:ligne 98
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\Connection.cs:ligne 810
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\command.cs:ligne 993
   à MySql.Data.MySqlClient.MySqlCommand.CheckState() dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\command.cs:ligne 326
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\command.cs:ligne 418
   à MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data.Entity\EFMySqlCommand.cs:ligne 118
   à System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   à System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   à System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   à System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   à System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass3.<GetResults>b__2()
   à System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass3.<GetResults>b__1()
   à System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   à System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 44
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 168]]></log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="207" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459525623678" level="ERROR" thread="11"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable><![CDATA[System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: There is already an open DataReader associated with this Connection which must be closed first.
   à MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\Interceptors\ExceptionInterceptor.cs:ligne 98
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\Connection.cs:ligne 810
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\command.cs:ligne 993
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data\command.cs:ligne 441
   à MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) dans d:\Research\FHRMS\Dependency\MySQL\Source\MySql.Data.Entity\EFMySqlCommand.cs:ligne 118
   à System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   à System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   à System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   à System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   à System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass3.<GetResults>b__2()
   à System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass3.<GetResults>b__1()
   à System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   à System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   à System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 44
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 168]]></log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="207" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459525923575" level="ERROR" thread="14"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable>System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
   à System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   à System.Data.Entity.Internal.InternalContext.Initialize()
   à System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   à System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   à System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   à System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.IEnumerable.GetEnumerator()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 46
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 170</log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="210" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459526102142" level="ERROR" thread="14"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable>System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
   à System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   à System.Data.Entity.Internal.InternalContext.Initialize()
   à System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   à System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   à System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   à System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.IEnumerable.GetEnumerator()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 46
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 170</log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="210" /></log4j:event>
<log4j:event logger="FHRMS.Automatics.Logger" timestamp="1459526136282" level="ERROR" thread="13"><log4j:message>Daily routine failed</log4j:message><log4j:properties><log4j:data name="log4net:HostName" value="DESKTOP-7AUTU63" /><log4j:data name="log4jmachinename" value="DESKTOP-7AUTU63" /><log4j:data name="LogFileName" value="All-logs.xml" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DESKTOP-7AUTU63\Arsslen" /><log4j:data name="log4japp" value="PhexonServer.vshost.exe" /></log4j:properties><log4j:throwable>System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
   à System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   à System.Data.Entity.Internal.InternalContext.Initialize()
   à System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   à System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   à System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   à System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.IEnumerable.GetEnumerator()
   à System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   à FHRMS.Automatics.PhexonPilot.Load() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 46
   à FHRMS.Automatics.PhexonPilot.DailyRoutine() dans e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs:ligne 170</log4j:throwable><log4j:locationInfo class="FHRMS.Automatics.PhexonPilot" method="DailyRoutine" file="e:\Research\FHRMS\FHRMS.Automatics\PhexonPilot.cs" line="210" /></log4j:event>
